name: smartcalc
description: A full-screen calculator app built on phone

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  torch_light: ^0.3.0

flutter:
  uses-material-design: true